
spring:
  application:
    name: currency-conversion-service
  config:
    import: optional:configserver:http://localhost:8888
  #jpa:
   # show-sql: true
    #defer-datasource-initialization: true
  #h2:
   # console:
    #  enabled: true
  #datasource:
   # url: jdbc:h2:mem:testdb
  sleuth:
    sampler:
      probability: 1.0 #trace toute les req (0.1 trace 10% des req)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8100
