

spring:
  application:
    name: naming-server
  sleuth:
    sampler:
      probability: 1.0 #trace toute les req (0.1 trace 10% des req)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761