spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tijdrame/git-localconfig-repo.git
          default-label: main
server:
  port: 8888
