
spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    #defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      sample-api:
        #max-retry-attempts: 
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
server:
  port: 8000